# fly.toml app configuration file generated for puhelinluettelo-server on 2023-05-02T18:43:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "puhelinluettelo-server"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
